package app

import("net/http";"strings";"time";"github.com/golang-jwt/jwt/v5";"github.com/google/uuid";"go.mongodb.org/mongo-driver/bson";"go.mongodb.org/mongo-driver/mongo";"golang.org/x/crypto/bcrypt";"github.com/gin-gonic/gin")
func(a *App)sessionCookieName()string{if a.cfg.CookieSecure{return "__Host-session"};return "session"}
func(a *App)sessionCookie(value string,maxAge int)http.Cookie{sameSite:=http.SameSiteLaxMode;if a.cfg.CookieSecure{sameSite=http.SameSiteNoneMode};return http.Cookie{Name:a.sessionCookieName(),Value:value,Path:"/",HttpOnly:true,Secure:a.cfg.CookieSecure,SameSite:sameSite,MaxAge:maxAge}}
func(a *App)issue(c *gin.Context,id string)error{t:=jwt.NewWithClaims(jwt.SigningMethodHS256,Claims{UserID:id,RegisteredClaims:jwt.RegisteredClaims{ExpiresAt:jwt.NewNumericDate(time.Now().Add(24*time.Hour)),IssuedAt:jwt.NewNumericDate(time.Now())}});s,e:=t.SignedString([]byte(a.cfg.JWTSecret));if e!=nil{return e};cookie:=a.sessionCookie(s,86400);http.SetCookie(c.Writer,&cookie);return nil}
func(a *App)signup(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){var in struct{Email,Password string};if c.ShouldBindJSON(&in)!=nil||validateCredentials(in.Email,in.Password)!=nil{fail(c,400,"VALIDATION_ERROR","Use a valid email and an 8-72 character password");return};hash,e:=bcrypt.GenerateFromPassword([]byte(in.Password),bcrypt.DefaultCost);if e!=nil{fail(c,500,"SERVER_ERROR","Could not create account");return};u:=User{ID:uuid.NewString(),Email:strings.ToLower(strings.TrimSpace(in.Email)),PasswordHash:string(hash),CreatedAt:time.Now().UTC()};if _,e=repo.db.Collection("users").InsertOne(c,u);e!=nil{if mongo.IsDuplicateKeyError(e){fail(c,409,"ACCOUNT_UNAVAILABLE","Unable to create account with those details");return};fail(c,500,"SERVER_ERROR","Could not create account");return};if e=a.issue(c,u.ID);e!=nil{fail(c,500,"SERVER_ERROR","Could not create session");return};ok(c,gin.H{"id":u.ID,"email":u.Email})}}
func(a *App)login(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){var in struct{Email,Password string};if c.ShouldBindJSON(&in)!=nil{fail(c,400,"VALIDATION_ERROR","Invalid JSON");return};var u User;e:=repo.db.Collection("users").FindOne(c,bson.M{"email":strings.ToLower(strings.TrimSpace(in.Email))}).Decode(&u);if e!=nil||bcrypt.CompareHashAndPassword([]byte(u.PasswordHash),[]byte(in.Password))!=nil{fail(c,401,"INVALID_CREDENTIALS","Email or password is incorrect");return};if e=a.issue(c,u.ID);e!=nil{fail(c,500,"SERVER_ERROR","Could not create session");return};ok(c,gin.H{"id":u.ID,"email":u.Email})}}
func(a *App)logout(c *gin.Context){cookie:=a.sessionCookie("",-1);http.SetCookie(c.Writer,&cookie);ok(c,nil)}
func(a *App)me(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){var u User;if e:=repo.db.Collection("users").FindOne(c,bson.M{"_id":userID(c)}).Decode(&u);e!=nil{fail(c,404,"NOT_FOUND","User not found");return};ok(c,gin.H{"id":u.ID,"email":u.Email})}}
