package app

import("crypto/rand";"encoding/base64";"net/http";"strings";"time";"github.com/gin-gonic/gin";"github.com/google/uuid";"go.mongodb.org/mongo-driver/bson";"go.mongodb.org/mongo-driver/mongo";"go.mongodb.org/mongo-driver/mongo/options")
func randomID()string{b:=make([]byte,9);_,_=rand.Read(b);return base64.RawURLEncoding.EncodeToString(b)}
func(a *App)createPoll(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){var in struct{Question string `json:"question"`;Options []string `json:"options"`;ExpiresAt *time.Time `json:"expiresAt"`};if c.ShouldBindJSON(&in)!=nil{fail(c,400,"VALIDATION_ERROR","Invalid JSON");return};opts,e:=validatePoll(in.Question,in.Options,in.ExpiresAt);if e!=nil{fail(c,400,"VALIDATION_ERROR",e.Error());return};now:=time.Now().UTC();p:=Poll{ID:randomID(),OwnerID:userID(c),Question:strings.TrimSpace(in.Question),Options:opts,Status:"active",CreatedAt:now,UpdatedAt:now,ExpiresAt:in.ExpiresAt};if _,e=repo.db.Collection("polls").InsertOne(c,p);e!=nil{fail(c,500,"SERVER_ERROR","Could not create poll");return};ok(c,p)}}
func(a *App)listPolls(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){cur,e:=repo.db.Collection("polls").Find(c,bson.M{"ownerId":userID(c)},options.Find().SetSort(bson.D{{Key:"createdAt",Value:-1}}));if e!=nil{fail(c,500,"SERVER_ERROR","Could not load polls");return};defer cur.Close(c);var polls []Poll;if e=cur.All(c,&polls);e!=nil{fail(c,500,"SERVER_ERROR","Could not load polls");return};ok(c,polls)}}
func(a *App)getPoll(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){var p Poll;if e:=repo.db.Collection("polls").FindOne(c,bson.M{"_id":c.Param("id")}).Decode(&p);e!=nil{fail(c,404,"NOT_FOUND","Poll not found");return};ok(c,p)}}
func(a *App)ownerPoll(c *gin.Context,repo *Repository)(*Poll,bool){var p Poll;if e:=repo.db.Collection("polls").FindOne(c,bson.M{"_id":c.Param("id")}).Decode(&p);e!=nil{fail(c,404,"NOT_FOUND","Poll not found");return nil,false};if p.OwnerID!=userID(c){fail(c,403,"FORBIDDEN","You do not own this poll");return nil,false};return &p,true}
func(a *App)updatePoll(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){p,good:=a.ownerPoll(c,repo);if !good{return};var in struct{Status string `json:"status"`};if c.ShouldBindJSON(&in)!=nil||(in.Status!="active"&&in.Status!="closed"){fail(c,400,"VALIDATION_ERROR","Status must be active or closed");return};if p.ExpiresAt!=nil&&p.ExpiresAt.Before(time.Now())&&in.Status=="active"{fail(c,409,"POLL_EXPIRED","Expired polls cannot be reopened");return};p.Status=in.Status;p.UpdatedAt=time.Now().UTC();if _,e:=repo.db.Collection("polls").ReplaceOne(c,bson.M{"_id":p.ID},p);e!=nil{fail(c,500,"SERVER_ERROR","Could not update poll");return};ok(c,p)}}
func(a *App)deletePoll(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){p,good:=a.ownerPoll(c,repo);if !good{return};if _,e:=repo.db.Collection("polls").DeleteOne(c,bson.M{"_id":p.ID});e!=nil{fail(c,500,"SERVER_ERROR","Could not delete poll");return};_,_=repo.db.Collection("votes").DeleteMany(c,bson.M{"pollId":p.ID});_ = repo.redis.Del(c,resultKey(p.ID)).Err();ok(c,nil)}}
func(a *App)results(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){var p Poll;if e:=repo.db.Collection("polls").FindOne(c,bson.M{"_id":c.Param("id")}).Decode(&p);e!=nil{fail(c,404,"NOT_FOUND","Poll not found");return};counts,e:=repo.counts(c,&p);if e!=nil{fail(c,503,"LIVE_RESULTS_UNAVAILABLE","Live results are temporarily unavailable");return};ok(c,makeResults(&p,counts))}}
func(a *App)vote(repo *Repository)gin.HandlerFunc{return func(c *gin.Context){var in struct{OptionID string `json:"optionId"`};if c.ShouldBindJSON(&in)!=nil||len(in.OptionID)<10{fail(c,400,"VALIDATION_ERROR","A valid option is required");return};var p Poll;if e:=repo.db.Collection("polls").FindOne(c,bson.M{"_id":c.Param("id")}).Decode(&p);e!=nil{fail(c,404,"NOT_FOUND","Poll not found");return};if p.Status!="active"||(p.ExpiresAt!=nil&&p.ExpiresAt.Before(time.Now())){fail(c,409,"POLL_CLOSED","This poll is no longer accepting votes");return};valid:=false;for _,o:=range p.Options{if o.ID==in.OptionID{valid=true}};if !valid{fail(c,400,"INVALID_OPTION","That option does not belong to this poll");return};voter:=a.getVoter(c);v:=Vote{ID:uuid.NewString(),PollID:p.ID,OptionID:in.OptionID,VoterID:voter,CreatedAt:time.Now().UTC()};if _,e:=repo.db.Collection("votes").InsertOne(c,v);e!=nil{if mongo.IsDuplicateKeyError(e){fail(c,409,"ALREADY_VOTED","You have already voted in this poll");return};fail(c,500,"SERVER_ERROR","Could not record vote");return};if e:=repo.redis.HIncrBy(c,resultKey(p.ID),in.OptionID,1).Err();e!=nil{fail(c,503,"LIVE_RESULTS_UNAVAILABLE","Vote recorded, but live results are temporarily unavailable");return};counts,e:=repo.counts(c,&p);if e!=nil{fail(c,503,"LIVE_RESULTS_UNAVAILABLE","Vote recorded, but results are temporarily unavailable");return};payload:=makeResults(&p,counts);encoded,_:=jsonMarshal(payload);if e=repo.redis.Publish(c,updateChannel(p.ID),encoded).Err();e!=nil{fail(c,503,"LIVE_RESULTS_UNAVAILABLE","Vote recorded, but live updates are temporarily unavailable");return};ok(c,payload)}}
func(a *App)getVoter(c *gin.Context)string{if id,e:=c.Cookie("voter_id");e==nil&&len(id)>10{return id};id:=uuid.NewString();http.SetCookie(c.Writer,&http.Cookie{Name:"voter_id",Value:id,Path:"/",HttpOnly:true,Secure:a.cfg.CookieSecure,SameSite:http.SameSiteLaxMode,MaxAge:31536000});return id}
