package app

import("context";"errors";"fmt";"log";"net/http";"strings";"time";"github.com/gin-contrib/cors";"github.com/gin-gonic/gin";"github.com/golang-jwt/jwt/v5";"github.com/redis/go-redis/v9";"go.mongodb.org/mongo-driver/mongo";"go.mongodb.org/mongo-driver/mongo/options")
func New(ctx context.Context,cfg Config)(*App,error){if e:=cfg.Validate();e!=nil{return nil,e};mc,e:=mongo.Connect(ctx,options.Client().ApplyURI(cfg.MongoURI));if e!=nil{return nil,fmt.Errorf("mongo connect: %w",e)};if e=mc.Ping(ctx,nil);e!=nil{return nil,fmt.Errorf("mongo ping: %w",e)};rc,e:=redis.ParseURL(cfg.RedisURL);if e!=nil{return nil,fmt.Errorf("redis url: %w",e)};r:=redis.NewClient(rc);if e=r.Ping(ctx).Err();e!=nil{return nil,fmt.Errorf("redis ping: %w",e)};a:=&App{cfg:cfg,mongoClient:mc,db:mc.Database(cfg.MongoDatabase),redis:r};repo:=&Repository{db:a.db,redis:r};if e=repo.setup(ctx);e!=nil{return nil,fmt.Errorf("database indexes: %w",e)};a.router=a.routes(repo);return a,nil}
func(a *App)Close(ctx context.Context)error{if a.httpServer!=nil{_ = a.httpServer.Shutdown(ctx)};if a.redis!=nil{_ = a.redis.Close()};if a.mongoClient!=nil{return a.mongoClient.Disconnect(ctx)};return nil}
func(a *App)Router()*gin.Engine{return a.router}
func(a *App)Serve(addr string)error{a.httpServer=&http.Server{Addr:addr,Handler:a.router,ReadHeaderTimeout:5*time.Second,ReadTimeout:15*time.Second,WriteTimeout:20*time.Second,IdleTimeout:60*time.Second};return a.httpServer.ListenAndServe()}
func(a *App)routes(repo *Repository)*gin.Engine{gin.SetMode(gin.ReleaseMode);r:=gin.New();r.Use(gin.Logger(),gin.Recovery(),bodyLimit(),cors.New(cors.Config{AllowOrigins:origins(a.cfg.AllowedOrigins),AllowMethods:[]string{"GET","POST","PATCH","DELETE","OPTIONS"},AllowHeaders:[]string{"Content-Type","Authorization","X-CSRF-Token"},AllowCredentials:true}));r.GET("/health",a.health);api:=r.Group("/api");auth:=api.Group("/auth");auth.Use(a.rateLimit("auth",20,time.Minute));auth.POST("/signup",a.signup(repo));auth.POST("/login",a.login(repo));auth.POST("/logout",a.logout);auth.GET("/me",a.requireAuth(),a.me(repo));polls:=api.Group("/polls");polls.GET("/:id",a.getPoll(repo));polls.GET("/:id/results",a.results(repo));polls.GET("/:id/ws",a.ws(repo));polls.POST("/:id/vote",a.rateLimit("vote",60,time.Minute),a.vote(repo));private:=api.Group("/polls",a.requireAuth());private.GET("",a.listPolls(repo));private.POST("",a.createPoll(repo));private.PATCH("/:id",a.updatePoll(repo));private.DELETE("/:id",a.deletePoll(repo));return r}
func bodyLimit()gin.HandlerFunc{return func(c *gin.Context){c.Request.Body=http.MaxBytesReader(c.Writer,c.Request.Body,64<<10);c.Next()}}
func(a *App)health(c *gin.Context){ctx,cancel:=context.WithTimeout(c,2*time.Second);defer cancel();if e:=a.mongoClient.Ping(ctx,nil);e!=nil{fail(c,503,"DEPENDENCY_UNAVAILABLE","MongoDB is unavailable");return};if e:=a.redis.Ping(ctx).Err();e!=nil{fail(c,503,"DEPENDENCY_UNAVAILABLE","Redis is unavailable");return};c.JSON(200,gin.H{"status":"ok"})}
func(a *App)rateLimit(name string,limit int,window time.Duration)gin.HandlerFunc{return func(c *gin.Context){key:="rate:"+name+":"+c.ClientIP();n,e:=a.redis.Incr(c,key).Result();if e==nil&&n==1{_ = a.redis.Expire(c,key,window).Err()};if e!=nil{log.Printf("rate limiter unavailable: %v",e)}else if n>int64(limit){c.Header("Retry-After",fmt.Sprintf("%d",int(window.Seconds())));fail(c,429,"RATE_LIMITED","Too many requests, please try again later");return};c.Next()}}
func fail(c *gin.Context,status int,code,message string){c.AbortWithStatusJSON(status,gin.H{"success":false,"error":gin.H{"code":code,"message":message}})};func ok(c *gin.Context,data any){c.JSON(200,gin.H{"success":true,"data":data})}
func(a *App)requireAuth()gin.HandlerFunc{return func(c *gin.Context){token,e:=c.Cookie("session");if e!=nil{token=strings.TrimPrefix(c.GetHeader("Authorization"),"Bearer ")};claims:=&Claims{};t,e:=jwt.ParseWithClaims(token,claims,func(t *jwt.Token)(any,error){if t.Method.Alg()!=jwt.SigningMethodHS256.Alg(){return nil,errors.New("unexpected signing method")};return []byte(a.cfg.JWTSecret),nil});if e!=nil||!t.Valid||claims.UserID==""{fail(c,401,"UNAUTHORIZED","Authentication required");return};c.Set("userID",claims.UserID);c.Next()}}
func userID(c *gin.Context)string{v,_:=c.Get("userID");s,_:=v.(string);return s}
